version: "2"
services:

  app:
    build:
      context: .
      cache_from:
        - ruby:2.5.1-alpine
        - salon_loaders
        - nyulibraries/salon_loaders:latest
        - nyulibraries/salon_loaders:$BRANCH_NO_SLASH
    image: salon_loaders
    environment:
      SALON_CLIENT_ID:
      SALON_CLIENT_SECRET:
      SALON_LOGIN_TOKEN_URL:
      SALON_LOAD_URL:

  test:
    build:
      context: .
      cache_from:
        - ruby:2.5.1-alpine
        - salon_loaders
        - nyulibraries/salon_loaders:latest
        - nyulibraries/salon_loaders:$BRANCH_NO_SLASH
    image: salon_loaders
    command: "bundle exec rake"
    environment:
      CI:
