version: "3.2"
services:

  app:
    image: salon_loaders
    build:
      context: .
      cache_from:
        - ruby:2.5.1-alpine
        - salon_loaders
        - nyulibraries/salon_loaders:latest
        - nyulibraries/salon_loaders:$BRANCH_NO_SLASH
    environment:
      SALON_CLIENT_ID:
      SALON_CLIENT_SECRET:
      SALON_LOGIN_TOKEN_URL:
      SALON_LOAD_URL:
      LIB_GUIDES_CLIENT_ID:
      LIB_GUIDES_CLIENT_SECRET:

  test:
    image: salon_loaders
    build:
      context: .
      cache_from:
        - ruby:2.5.1-alpine
        - salon_loaders
        - nyulibraries/salon_loaders:latest
        - nyulibraries/salon_loaders:$BRANCH_NO_SLASH
    command: "bundle exec rake"
    environment:
      CI:

  scan:
    image: salon_loaders_scan
    build:
      context: .
      dockerfile: Dockerfile.scan
      args:
        TOKEN: $AQUA_MICROSCANNER_TOKEN
