version: 2
jobs:
  build:
    docker:
      - image: docker:stable-git
    working_directory: ~/app
    steps:
      - checkout
      - setup_remote_docker

      - run:
          name: Build container
          command: |
            docker build -t app .

      - run:
          name: Run tests
          command: |
            docker run app rspec
