# https://circleci.com/blog/how-to-build-a-docker-image-on-circleci-2-0/
version: 2
jobs:
  build:
    docker:
      - image: docker:18.05.0-ce-git
    working_directory: ~/app
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: |
            apk add --no-cache \
              py-pip
            pip install \
              docker-compose==1.16.1
      - run:
          name: Pull docker images
          command: |
            script/pull_docker.sh
      - run:
          name: Run tests
          command: |
            touch secrets.env
            export BRANCH_NO_SLASH=${CIRCLE_BRANCH//\//_}
            docker-compose run test
      # - run:
      #     name: Scan image
      #     command: |
      #       docker-compose build app && docker-compose build --no-cache scan
      - run:
          name: Docker login
          command: |
            docker login -u "$DOCKER_USERNAME" --password "$DOCKER_PASSWORD"
      - run:
          name: Push docker images
          command: |
            script/push_docker.sh
